opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - implicit_return
  - joined_default_parameter
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - single_test_class
  - unneeded_parentheses_in_closure_argument
  - private_over_fileprivate
  - sorted_imports

included:
  - Sources
  - Tests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - fastlane
  - Pods
  - Vendor
  - build
  - Tests

nesting:
  type_level: 3

