# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: mkdir lint
      - run: swiftlint lint --strict --reporter junit | tee lint/result.junit
      - store_test_results:
          path: lint
  test:
    macos:
      xcode: "10.1.0"
    environment:
    steps:
      - checkout
      - run: mkdir test_output
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: test_output

workflows:
  version: 2
  build:
    jobs:
      - swiftlint
      - test
