version: 2.1

executors:

  mac:
    macos:
      xcode: "10.1.0"

  go:
    docker:
      - image: circleci/golang:1.8

  linux:
    docker:
      - image: norionomura/swift:latest

commands:

  persist:
    parameters:
      path:
        type: string
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.path >>

  attach:
    steps:
      - attach_workspace:
          at: .

jobs:

  resolve:
    executor: mac
    steps:
      - checkout
      - run: swift package resolve
      - persist:
          path: .build

  build_package:
    executor: mac
    parameters:
      artifacts:
        default: artifacts
        type: string
    steps:
      - checkout
      - attach
      - run:
          command: make package
          name: Build package
      - run: mkdir -p << parameters.artifacts >>
      - run:
          command: mv "${CIRCLE_PROJECT_REPONAME}.pkg" << parameters.artifacts >>
          name: Move artifacts
      - persist:
          path: << parameters.artifacts >>

  generate_changelog:
    executor: mac
    parameters:
      artifacts:
        default: changelog
        type: string
    steps:
      - checkout
      - run: mkdir -p << parameters.artifacts >>
      - attach
      - run: FINCH_CONFIG=.finch/release_config.yml swift run finch compare > << parameters.artifacts >>/changelog.md
      - persist:
          path: << parameters.artifacts >>

  publish_release:
    executor: go
    steps:
      - attach
      - run:
          command: |
            go get github.com/tcnksm/ghr
            ghr \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -n ${CIRCLE_TAG} \
              -b "$(cat changelog/changelog.md)" \
              -delete \
              -replace \
              -draft \
              -prerelease \
              ${CIRCLE_TAG} "artifacts/${CIRCLE_PROJECT_REPONAME}.pkg"
          name: Publish release to GitHub

  swiftlint:
    executor: mac
    parameters:
      lint-cache-dir:
        default: lint/cache
        type: string
      lint-results-dir:
        default: build/reports/lint
        type: string
      lint-bin:
        default: .build/debug/swiftlint
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-lint-cache-{{ arch }}-{{ .Branch }}
            - v{{ .Environment.CACHE_VERSION }}-lint-cache-{{ arch }}
          name: Restore lint cache
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-build-cache-{{ arch }}-{{ checksum "Package.resolved" }}
          name: Restore bin cache
      - run: mkdir -p << parameters.lint-cache-dir >> << parameters.lint-results-dir >>
      - run:
          command: |
            executable=$(echo '<< parameters.lint-bin >>')
            if ! [ $(command -v $executable) ]; then
              executable='swift run swiftlint'
            fi

            eval $executable lint --strict --reporter junit --cache-path << parameters.lint-cache-dir >> | tee << parameters.lint-results-dir >>/results.xml
          name: Lint
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-build-cache-{{ arch }}-{{ checksum "Package.resolved" }}
          paths:
            - << parameters.lint-bin >>
          name: Save bin cache
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-lint-cache-{{ arch }}-{{ .Branch }}
          paths:
            - << parameters.lint-cache-dir >>
          name: Save lint cache
      - store_artifacts:
          path: << parameters.lint-results-dir >>

  test:
    executor: mac
    parameters:
      test-results-dir:
        default: build/reports/test
        type: string
    steps:
      - checkout
      - attach
      - run: mkdir -p << parameters.test-results-dir >>
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: << parameters.test-results-dir >>

  generate_linux_main:
    executor: mac
    steps:
      - checkout
      - attach
      - run: swift test --generate-linuxmain
      - persist_to_workspace:
          root: .
          paths:
            - Tests/LinuxMain.swift
            - Tests/FinchAppTests/XCTestManifests.swift

  test_linux:
    executor: linux
    parameters:
      test-results-dir:
        default: build/reports/test
        type: string
    steps:
      - checkout
      - run: mkdir -p << parameters.test-results-dir >>
      - run:
          name: Run tests
          command: swift test
      - store_test_results:
          path: << parameters.test-results-dir >>

workflows:
  build:
    jobs:
      - swiftlint:
          filters:
            tags:
              only: /.*/
      - resolve:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - resolve
      - build_package:
          requires:
            - resolve
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - generate_changelog:
          requires:
            - resolve
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish_release:
          requires:
            - swiftlint
            - test
            - build_package
            - generate_changelog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - generate_linux_main:
          requires:
            - resolve
      - test_linux:
          requires:
            - generate_linux_main
