version: 2.1
executors:
  mac:
    macos:
      xcode: "10.1.0"
  go:
    docker:
      - image: circleci/golang:1.8
jobs:
  build_package:
    executor: mac
    parameters:
      artifacts-path:
        default: artifacts
        type: string
    steps:
      - checkout
      - run:
          command: make update_build_number
          name: Update build number
      - run:
          command: make package
          name: Build package
      - run: mkdir -p << parameters.artifacts-path >>
      - run:
          command: mv "$CIRCLE_PROJECT_REPONAME.pkg" << parameters.artifacts-path >>
          name: Move artifacts
      - persist_to_workspace:
          root: << parameters.artifacts-path >>
          paths:
            - .
  publish_release:
    executor: go
    parameters:
      artifacts-path:
        default: artifacts
        type: string
    steps:
      - run: mkdir -p << parameters.artifacts-path >>
      - attach_workspace:
          at: << parameters.artifacts-path >>
      - run:
          command: |
            go get github.com/tcnksm/ghr
            ghr \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -n ${CIRCLE_TAG} \
              -delete \
              -prerelease \
              ${CIRCLE_TAG} << parameters.artifacts-path >>
          name: Publish release to GitHub
  swiftlint:
    executor: mac
    parameters:
      lint-cache-dir:
        default: lint/cache
        type: string
      lint-results-dir:
        default: build/reports
        type: string
      lint-bin:
        default: .build/debug/swiftlint
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-lint-cache-{{ arch }}
          name: Restore lint cache
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-build-cache-{{ arch }}-{{ checksum "Package.resolved" }}
          name: Restore bin cache
      - run: mkdir -p << parameters.lint-cache-dir >> << parameters.lint-results-dir >>
      - run:
          command: |
            executable=$(echo '<< parameters.lint-bin >>')
            if ! [ $(command -v $executable) ]; then
              executable='swift run swiftlint'
            fi

            eval $executable lint --strict --reporter junit --cache-path << parameters.lint-cache-dir >> | tee << parameters.lint-results-dir >>/lint/results.xml
          name: Lint
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-build-cache-{{ arch }}-{{ checksum "Package.resolved" }}
          paths:
            - << parameters.lint-bin >>
          name: Save bin cache
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-lint-cache-{{ arch }}
          paths:
            - << parameters.lint-cache-dir >>
          name: Save lint cache
      - store_test_results:
          path: << parameters.lint-results-dir >>
  test:
    executor: mac
    parameters:
      test-results-dir:
        default: build/reports/test
        type: string
    steps:
      - checkout
      - run: mkdir -p << parameters.test-results-dir >>
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: << parameters.test-results-dir >>

workflows:
  build:
    jobs:
      - swiftlint
      - test
      - build_package:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish_release:
          requires:
            - swiftlint
            - test
            - build_package
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
