version: 2.1
executors:
  mac:
    macos:
      xcode: "10.1.0"
  go:
    docker:
      - image: circleci/golang:1.8
jobs:
  build_package:
    executor: mac
    environment:
      ARTIFACTS_PATH: artifacts
    steps:
      - checkout
      - run:
          command: make update_build_number
          name: Update build number
      - run:
          command: make package
          name: Build package
      - run: mkdir -p artifacts
      - run:
          command: mv "$CIRCLE_PROJECT_REPONAME.pkg" $ARTIFACTS_PATH
          name: Move artifacts
      - persist_to_workspace:
          root: ./{{ .Environment.ARTIFACTS_PATH }}
          paths:
            - .
  publish_release:
    executor: go
    environment:
      ARTIFACTS_PATH: artifacts
    steps:
      - run: mkdir -p $ARTIFACTS_PATH
      - attach_workspace:
          at: ./{{ .Environment.ARTIFACTS_PATH }}
      - run:
          command: |
            go get github.com/tcnksm/ghr
            ghr \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -n ${CIRCLE_TAG} \
              -delete \
              -prerelease \
              ${CIRCLE_TAG} ${ARTIFACTS_PATH}
          name: Publish release to GitHub
  swiftlint:
    executor: mac
    environment:
      SWIFTLINT_CACHE_PATH: lint/cache
      SWIFTLINT_OUTPUT_PATH: build/reports/lint
      SWIFTLINT_BIN_PATH: .build/debug/swiftlint
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-lint-cache-{{ arch }}
          name: Restore lint cache
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-build-cache-{{ arch }}-{{ checksum "Package.resolved" }}
          name: Restore bin cache
      - run: mkdir -p $SWIFTLINT_OUTPUT_PATH $SWIFTLINT_CACHE_PATH
      - run:
          command: |
            executable=$SWIFTLINT_BIN_PATH
            if ! [ $(command -v $executable) ]; then
              executable='swift run swiftlint'
            fi

            eval $executable lint --strict --reporter junit --cache-path $SWIFTLINT_CACHE_PATH | tee $SWIFTLINT_OUTPUT_PATH/junit.xml
          name: Lint
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-build-cache-{{ arch }}-{{ checksum "Package.resolved" }}
          paths:
            - ./{{ .Environment.SWIFTLINT_BIN_PATH }}
          name: Save bin cache
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-lint-cache-{{ arch }}
          paths:
            - ./{{ .Environment.SWIFTLINT_CACHE_PATH }}
          name: Save lint cache
      - store_test_results:
          path: ./{{ .Environment.SWIFTLINT_OUTPUT_PATH }}
  test:
    executor: mac
    environment:
      TEST_OUTPUT_PATH: build/reports/test
    steps:
      - checkout
      - run: mkdir -p $TEST_OUTPUT_PATH
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: ./{{ .Environment.TEST_OUTPUT_PATH }}

workflows:
  version: 2.1
  build:
    jobs:
      - swiftlint
      - test
      - build_package:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish_release:
          requires:
            - swiftlint
            - test
            - build_package
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
