# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  swiftlint:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-build-cache-{{ arch }}-{{ checksum "Package.resolved" }}
            - v{{ .Environment.CACHE_VERSION }}-build-cache-{{ arch }}
            - v{{ .Environment.CACHE_VERSION }}-build-cache
      - run: mkdir -p build/reports/lint
      - run:
          command: |-
            executable=$(swift build --show-bin-path)/swiftlint
            if ! [ $(command -v $executable) ]; then
              executable='swift run swiftlint'
            fi

            eval $executable lint --strict --reporter junit | tee build/reports/lint/junit.xml
          name: Lint
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-build-cache-{{ arch }}-{{ checksum "Package.resolved" }}
          paths:
            - $(swift build --show-bin-path)
      - store_test_results:
          path: build/reports/lint
  test:
    macos:
      xcode: "10.1.0"
    environment:
    steps:
      - checkout
      - run: mkdir -p build/reports/test
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: build/reports/test

workflows:
  version: 2
  build:
    jobs:
      - swiftlint
      - test
