# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: mkdir -p build/reports/lint
      - run: swiftlint lint --strict --reporter junit | tee build/reports/lint/junit.xml
      - store_test_results:
          path: build/reports/lint
  test:
    macos:
      xcode: "10.1.0"
    environment:
    steps:
      - checkout
      - run: mkdir -p build/reports/test
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: build/reports/test

workflows:
  version: 2
  build:
    jobs:
      - swiftlint
      - test
