name: Lint

on: pull_request

jobs:
  lint:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint_build
    steps:
      - uses: actions/checkout@v2
      - name: Install mint
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install mint
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
      - name: Bootstrap mint
        run: mint bootstrap
      - name: SwiftLint
        run: mint run swiftlint swiftlint --strict
      - name: SwiftFormat
        run: mint run swiftformat swiftformat --lint .
