name: Release

on:
  create:
    tags: '*'

jobs:
  publish_release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Package
        run: make package
      - name: Generate Changelog
        env:
          FINCH_CONFIG: .finch/release_config.yml
        run: swift run finch compare > changelog.md
      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh release create ${GITHUB_REF} -p -F changelog.md Finch.pkg
