name: Test

on: pull_request

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: make test

  generate_linuxmain:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make update_build_number
      - run: make linuxmain
      - name: Archive Linux Testing Files
        uses: actions/upload-artifact@v2
        with:
          name: linux-test-dependencies
          path: |
            LinuxMain.swift
            Tests/XCTestManifests.swift

  test_linux:
    runs-on: ubuntu-latest
    needs: generate_linuxmain
    steps:
      - uses: actions/checkout@v2
      - name: Unarchive Linux Testing Files
        uses: actions/download-artifact@v2
        with:
          name: linux-test-dependencies
      - run: make update_build_number
      - name: Run Tests
        run: make test
